name: medseg_unet
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pandas
  - pydicom
  - pytest
  - pip
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - nibabel
  - tqdm
  - pyyaml
  - rich
  - pip:
      - monai
      - typer
      - fastapi
      - uvicorn
      - python-multipart
      - opencv-python
      - boto3
      - google-cloud-storage
      - prometheus-client
      - wandb
